
const provienceData = [
    { name: '黑龙江', area: '东北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '吉林', area: '东北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '辽宁', area: '东北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '内蒙古', area: '其他', type: 'areaCenterCity', InValue: '0' },
    { name: '北京', area: '华北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '天津', area: '华北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '河北', area: '华北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '山东', area: '华北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '山西', area: '华北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '江苏', area: '华东大区', type: 'areaCenterCity', InValue: '0' },
    { name: '上海', area: '华东大区', type: 'areaCenterCity', InValue: '0' },
    { name: '浙江', area: '华东大区', type: 'areaCenterCity', InValue: '0' },
    { name: '福建', area: '华南大区', type: 'areaCenterCity', InValue: '0' },
    { name: '广东', area: '华南大区', type: 'areaCenterCity', InValue: '0' },
    { name: '海南', area: '华南大区', type: 'areaCenterCity', InValue: '0' },
    { name: '台湾', area: '其他', type: 'areaCenterCity', InValue: '0' },
    { name: '香港', area: '其他', type: 'areaCenterCity', InValue: '0' },
    { name: '澳门', area: '其他', type: 'areaCenterCity', InValue: '0' },
    { name: '河南', area: '华北大区', type: 'areaCenterCity', InValue: '0' },
    { name: '安徽', area: '华中大区', type: 'areaCenterCity', InValue: '0' },
    { name: '江西', area: '华中大区', type: 'areaCenterCity', InValue: '0' },
    { name: '广东', area: '华南大区', type: 'areaCenterCity', InValue: '0' },
    { name: '陕西', area: '华西大区', type: 'areaCenterCity', InValue: '0' },
    { name: '湖北', area: '华中大区', type: 'areaCenterCity', InValue: '0' },
    { name: '湖南', area: '华中大区', type: 'areaCenterCity', InValue: '0' },
    { name: '广西', area: '华南大区', type: 'areaCenterCity', InValue: '0' },
    { name: '宁夏', area: '华西大区', type: 'areaCenterCity', InValue: '0' },
    { name: '重庆', area: '华西大区', type: 'areaCenterCity', InValue: '0' },
    { name: '贵州', area: '华西大区', type: 'areaCenterCity', InValue: '0' },
    { name: '四川', area: '华西大区', type: 'areaCenterCity', InValue: '0' },
    { name: '云南', area: '华西大区', type: 'areaCenterCity', InValue: '0' },
    { name: '甘肃', area: '华西大区', type: 'areaCenterCity', InValue: '0' },
    { name: '青海', area: '其他', type: 'areaCenterCity', InValue: '0' },
    { name: '西藏', area: '其他', type: 'areaCenterCity', InValue: '0' },
    { name: '新疆', area: '其他', type: 'areaCenterCity', InValue: '0' }
];

export {provienceData}